import type { User, Report, Comment, Notification } from "./types"

export const MOCK_USERS: User[] = [
  {
    id: "user1",
    email: "ahmad@gmail.com",
    name: "Ahmad bin Ibrahim",
    avatarSeed: "ahmad-seed",
    points: 450,
    badges: ["pemula", "penolong"],
    isPublic: true,
    isBanned: false,
    isAdmin: false,
    warnings: 0,
    created: "2025-12-01T08:00:00Z",
    updated: "2026-02-08T10:00:00Z",
  },
  {
    id: "user2",
    email: "siti@gmail.com",
    name: "Siti Nurhaliza",
    avatarSeed: "siti-seed",
    points: 780,
    badges: ["pemula", "penolong", "penyelesai"],
    isPublic: true,
    isBanned: false,
    isAdmin: false,
    warnings: 0,
    created: "2025-11-15T08:00:00Z",
    updated: "2026-02-07T10:00:00Z",
  },
  {
    id: "user3",
    email: "raj@gmail.com",
    name: "Raj Kumar",
    avatarSeed: "raj-seed",
    points: 320,
    badges: ["pemula"],
    isPublic: false,
    isBanned: false,
    isAdmin: false,
    warnings: 0,
    created: "2026-01-05T08:00:00Z",
    updated: "2026-02-08T10:00:00Z",
  },
  {
    id: "admin1",
    email: "admin@example.com",
    name: "Admin Moderator",
    avatarSeed: "admin-seed",
    points: 1200,
    badges: ["pemula", "penolong", "penyelesai"],
    isPublic: true,
    isBanned: false,
    isAdmin: true,
    warnings: 0,
    created: "2025-10-01T08:00:00Z",
    updated: "2026-02-08T10:00:00Z",
  },
  {
    id: "user4",
    email: "mei@gmail.com",
    name: "Tan Mei Ling",
    avatarSeed: "mei-seed",
    points: 195,
    badges: ["pemula"],
    isPublic: true,
    isBanned: false,
    isAdmin: false,
    warnings: 0,
    created: "2026-01-10T08:00:00Z",
    updated: "2026-02-06T10:00:00Z",
  },
  {
    id: "user5",
    email: "ali@gmail.com",
    name: "Ali Hassan",
    avatarSeed: "ali-seed",
    points: 560,
    badges: ["pemula", "penolong"],
    isPublic: true,
    isBanned: false,
    isAdmin: false,
    warnings: 1,
    created: "2025-12-20T08:00:00Z",
    updated: "2026-02-08T10:00:00Z",
  },
]

export const MOCK_REPORTS: Report[] = [
  {
    id: "rpt1",
    title: "Lubang besar di Jalan Ampang dekat KLCC",
    description:
      "Lubang sangat besar dan dalam di jalan utama. Sudah menyebabkan beberapa kereta rosak tayar. Sangat bahaya terutama waktu malam. Perlu dibaiki segera sebelum ada kemalangan.",
    category: "jalan_raya",
    photos: [],
    latitude: 3.1569,
    longitude: 101.7123,
    address: "Jalan Ampang, 50450 Kuala Lumpur",
    landmark: "Near KLCC Twin Towers",
    status: "open",
    createdBy: "user1",
    followers: ["user1", "user2", "user3"],
    upvotes: ["user2", "user3", "user4", "user5"],
    upvoteCount: 4,
    confirmations: [],
    confirmationCount: 0,
    flagCount: 0,
    flaggedBy: [],
    isHidden: false,
    commentsLocked: false,
    created: "2026-02-08T06:30:00Z",
    updated: "2026-02-08T10:00:00Z",
    expand: { createdBy: MOCK_USERS[0] },
  },
  {
    id: "rpt2",
    title: "Lampu jalan rosak di Taman Desa",
    description:
      "Lampu jalan di sepanjang jalan utama Taman Desa sudah rosak 3 minggu. Kawasan sangat gelap pada waktu malam. Penduduk rasa tidak selamat terutama wanita dan kanak-kanak.",
    category: "lampu_jalan",
    photos: [],
    latitude: 3.1048,
    longitude: 101.6773,
    address: "Jalan Desa Utama, Taman Desa, 58100 KL",
    landmark: "Near Taman Desa Park",
    status: "acknowledged",
    createdBy: "user2",
    followers: ["user2", "user1"],
    upvotes: ["user1", "user3"],
    upvoteCount: 2,
    confirmations: [],
    confirmationCount: 0,
    flagCount: 0,
    flaggedBy: [],
    isHidden: false,
    commentsLocked: false,
    created: "2026-02-07T14:00:00Z",
    updated: "2026-02-08T09:00:00Z",
    expand: { createdBy: MOCK_USERS[1] },
  },
  {
    id: "rpt3",
    title: "Sampah bertimbun di Pasar Chow Kit",
    description:
      "Sampah sarap bertimbun di tepi jalan dekat pasar. Bau sangat busuk dan menarik tikus serta lalat. Tong sampah penuh dan tidak dikutip selama seminggu.",
    category: "sampah_sarap",
    photos: [],
    latitude: 3.1655,
    longitude: 101.6985,
    address: "Jalan Raja Muda, Chow Kit, 50300 KL",
    landmark: "Pasar Chow Kit area",
    status: "in_progress",
    createdBy: "user3",
    followers: ["user3", "user1", "user2", "user5"],
    upvotes: ["user1", "user2", "user4", "user5", "admin1"],
    upvoteCount: 5,
    confirmations: [],
    confirmationCount: 0,
    flagCount: 0,
    flaggedBy: [],
    isHidden: false,
    commentsLocked: false,
    created: "2026-02-06T09:00:00Z",
    updated: "2026-02-08T08:00:00Z",
    expand: { createdBy: MOCK_USERS[2] },
  },
  {
    id: "rpt4",
    title: "Longkang tersumbat di Bangsar South",
    description:
      "Longkang di tepi jalan tersumbat dengan sampah dan daun. Bila hujan lebat, air naik ke jalan dan membanjiri kawasan parking. Ini sudah terjadi 3 kali bulan ini.",
    category: "longkang_tersumbat",
    photos: [],
    latitude: 3.1109,
    longitude: 101.6656,
    address: "Jalan Kerinchi, Bangsar South, 59200 KL",
    landmark: "Near The Vertical business suites",
    status: "closed",
    createdBy: "user2",
    followers: ["user2", "user4"],
    upvotes: ["user1", "user4"],
    upvoteCount: 2,
    confirmations: ["admin1"],
    confirmationCount: 1,
    flagCount: 0,
    flaggedBy: [],
    isHidden: false,
    commentsLocked: false,
    created: "2026-01-25T11:00:00Z",
    updated: "2026-02-05T16:00:00Z",
    expand: { createdBy: MOCK_USERS[1] },
  },
  {
    id: "rpt5",
    title: "Vandalisme di taman permainan Petaling Jaya",
    description:
      "Alat permainan kanak-kanak di taman telah dirosakkan dan dicatit dengan graffiti. Buaian patah dan berbahaya untuk kanak-kanak. Perlu dibaiki atau diganti.",
    category: "vandalisme",
    photos: [],
    latitude: 3.1073,
    longitude: 101.6067,
    address: "Taman Jaya, Petaling Jaya, 46000",
    landmark: "Taman Jaya Playground",
    status: "open",
    createdBy: "user4",
    followers: ["user4", "user2"],
    upvotes: ["user1", "user2", "user3"],
    upvoteCount: 3,
    confirmations: [],
    confirmationCount: 0,
    flagCount: 0,
    flaggedBy: [],
    isHidden: false,
    commentsLocked: false,
    created: "2026-02-08T08:00:00Z",
    updated: "2026-02-08T08:00:00Z",
    expand: { createdBy: MOCK_USERS[4] },
  },
  {
    id: "rpt6",
    title: "Kucing terbiar banyak di Shah Alam",
    description:
      "Ada lebih 10 ekor kucing terbiar di kawasan perumahan ini. Mereka kelihatan sakit dan kurus. Perlu bantuan daripada pihak berkuasa atau NGO haiwan.",
    category: "haiwan_terbiar",
    photos: [],
    latitude: 3.0733,
    longitude: 101.5185,
    address: "Seksyen 7, Shah Alam, 40000",
    landmark: "Near Shah Alam Lake Gardens",
    status: "open",
    createdBy: "user5",
    followers: ["user5", "user2"],
    upvotes: ["user2"],
    upvoteCount: 1,
    confirmations: [],
    confirmationCount: 0,
    flagCount: 0,
    flaggedBy: [],
    isHidden: false,
    commentsLocked: false,
    created: "2026-02-09T02:00:00Z",
    updated: "2026-02-09T02:00:00Z",
    expand: { createdBy: MOCK_USERS[5] },
  },
]

export const MOCK_COMMENTS: Comment[] = [
  {
    id: "cmt1",
    reportId: "rpt1",
    userId: "user2",
    content: "Saya juga nampak lubang ini semalam. Sangat bahaya! Harap pihak berkuasa cepat baiki.",
    photos: [],
    parentId: null,
    reactions: { like: ["user1", "user3"], support: ["user4"], urgent: ["user5"] },
    isHidden: false,
    created: "2026-02-08T07:00:00Z",
    updated: "2026-02-08T07:00:00Z",
    expand: { userId: MOCK_USERS[1] },
  },
  {
    id: "cmt2",
    reportId: "rpt1",
    userId: "user3",
    content: "Tayar kereta saya rosak sebab lubang ini. Kena tukar tayar baru. DBKL perlu ambil tindakan!",
    photos: [],
    parentId: null,
    reactions: { like: ["user1"], support: ["user2", "user5"], urgent: [] },
    isHidden: false,
    created: "2026-02-08T08:30:00Z",
    updated: "2026-02-08T08:30:00Z",
    expand: { userId: MOCK_USERS[2] },
  },
  {
    id: "cmt3",
    reportId: "rpt1",
    userId: "user1",
    content: "Terima kasih semua yang upvote. Semoga pihak berkuasa nampak laporan ini.",
    photos: [],
    parentId: "cmt2",
    reactions: { like: ["user2"], support: [], urgent: [] },
    isHidden: false,
    created: "2026-02-08T09:00:00Z",
    updated: "2026-02-08T09:00:00Z",
    expand: { userId: MOCK_USERS[0] },
  },
  {
    id: "cmt4",
    reportId: "rpt3",
    userId: "admin1",
    content: "Terima kasih atas laporan ini. Kami telah hubungi pihak SWCorp untuk kutip sampah. Dijangka selesai dalam 48 jam.",
    photos: [],
    parentId: null,
    reactions: { like: ["user3", "user1", "user5"], support: [], urgent: [] },
    isHidden: false,
    created: "2026-02-07T10:00:00Z",
    updated: "2026-02-07T10:00:00Z",
    expand: { userId: MOCK_USERS[3] },
  },
  {
    id: "cmt5",
    reportId: "rpt2",
    userId: "user5",
    content: "Kawasan ini memang gelap. Saya terpaksa guna lampu telefon setiap malam.",
    photos: [],
    parentId: null,
    reactions: { like: [], support: ["user2"], urgent: ["user1"] },
    isHidden: false,
    created: "2026-02-07T20:00:00Z",
    updated: "2026-02-07T20:00:00Z",
    expand: { userId: MOCK_USERS[5] },
  },
]

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif1",
    userId: "user1",
    type: "upvote",
    title: "Report upvoted",
    message: "Your report received 5 upvotes!",
    relatedReportId: "rpt1",
    relatedCommentId: "",
    isRead: false,
    created: "2026-02-08T10:00:00Z",
  },
  {
    id: "notif2",
    userId: "user1",
    type: "comment",
    title: "New comment",
    message: "Siti Nurhaliza commented on your report",
    relatedReportId: "rpt1",
    relatedCommentId: "cmt1",
    isRead: false,
    created: "2026-02-08T07:00:00Z",
  },
  {
    id: "notif3",
    userId: "user1",
    type: "badge",
    title: "Badge unlocked!",
    message: "You earned the Pemula badge!",
    relatedReportId: "",
    relatedCommentId: "",
    isRead: true,
    created: "2026-02-08T06:35:00Z",
  },
]

export const LEADERBOARD_USERS = [...MOCK_USERS]
  .sort((a, b) => b.points - a.points)
  .map((u, i) => ({ ...u, rank: i + 1 }))
